
version: '3.8'
services:
  db:
    image: postgres:16.4
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: punch-clock
    ports:
    - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: meu-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  app:
    build:
      dockerfile: Dockerfile
    container_name: punch-clock-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/punch-clock
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    depends_on:
       - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

