
version: '3.8'
services:
  database:
    image: postgres:16.4
    container_name: db-punch-clock
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: punch-clock
    ports:
    - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: meu-pgadmin-clock
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  app:
    build:
      dockerfile: Dockerfile
    container_name: punch-clock-api
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: punch-clock
    ports:
      - "8080:8080"
    depends_on:
       - database
    networks:
      - app-network

volumes:
  pgadmin-data:
  postgres-data:

networks:
  app-network:


