
version: '3.8'
services:
  db:
    image: postgres:16.4
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: punch_clock
    ports:
    - "5432:5432"
    networks:
      - app-network


  app:
    build:
      dockerfile: Dockerfile
    container_name: punch-clock-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/punch_clock
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

